# https://github.com/BetaHuhn/repo-file-sync-action
OpenIMSDK/openim-sdk-core:
  - source: LICENSE
    dest: LICENSE  
  - source: .gitingore
    dest: .gitingore
  - source: .golangci.yml
    dest: .golangci.yml
  - source: workflows/
    dest: .github/workflows/
    replace: false
    exclude: |
      e2e-test.yml

group:
  repos: |
    OpenIMSDK/OpenIM-Docs
    OpenIMSDK/community
  files: 
    - source: .gitingore
      dest: .gitingore
    - source: LICENSE
      dest: LICENSE
    - source: .github/sync_docs.yml
      dest: .github/sync_docs.yml