# https://github.com/BetaHuhn/repo-file-sync-action
# Synchronization for the.github repository
OpenIMSDK/.github:
  - source: LICENSE
    dest: LICENSE 
  - source: script/LICENSE/
    dest: scripts/LICENSE/
    replace: true
  - source: .github/
    dest: .github/
    replace: true
    exclude: |
      workflows/
      sync.yml

OpenIMSDK/community:
  - source: LICENSE
    dest: LICENSE 
  - source: script/LICENSE/
    dest: scripts/LICENSE/
    replace: true
  - source: .github/workflows/
    dest: .github/workflows/
    exclude:
      - e2e-test.yml
      - sync.yml
  - source: .github/
    dest: .github/
    replace: true
    exclude: |
      sync.yml

OpenIMSDK/openim-sdk-core:
  - source: LICENSE
    dest: LICENSE 
  - source: script/LICENSE/
    dest: scripts/LICENSE/
    replace: true
  - source: .github/
    dest: .github/
    replace: true
    exclude: |
      workflows/
      sync.yml

# group:
#   repos: |
#     OpenIMSDK/OpenIM-Docs
#     OpenIMSDK/community
#   files: 
#     - source: .gitingore
#       dest: .gitingore
#     - source: LICENSE
#       dest: LICENSE
#       replace: false
#     - source: .github/sync_docs.yml
#       dest: .github/sync_docs.yml
#     - source: workflows/
#       dest: .github/workflows/
#       exclude: |
#         e2e-test.yml