# https://github.com/BetaHuhn/repo-file-sync-action
OpenIMSDK/community:
  - source: LICENSE
    dest: LICENSE 
  - source: .golangci.yml
    dest: .golangci.yml
  - source: .githubworkflows/
    dest: .github/workflows/
    replace: true
    exclude: |
      e2e-test.yml

# group:
#   repos: |
#     OpenIMSDK/OpenIM-Docs
#     OpenIMSDK/community
#   files: 
#     - source: .gitingore
#       dest: .gitingore
#     - source: LICENSE
#       dest: LICENSE
#       replace: false
#     - source: .github/sync_docs.yml
#       dest: .github/sync_docs.yml
#     - source: workflows/
#       dest: .github/workflows/
#       exclude: |
#         e2e-test.yml