---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    # 使用重写后的路径进行路由
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
  name: sdk-server-ingress
spec:
  rules:
    - host: k8s.open-im-test.rentsoft.cn
      http:
        paths:
          - backend:
              service:
                name: sdk-server
                port:
                  number: 10003
            path: /sdk-server/(.*)
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
       proxy_set_header Upgrade $http_upgrade;
       proxy_http_version 1.1;
       proxy_set_header X-Forwarded-Host $http_host;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header X-Forwarded-For $remote_addr;
       proxy_set_header Host $host;
       proxy_set_header Connection "upgrade";
       proxy_cache_bypass $http_upgrade;
       }
     # 使用重写后的路径进行路由
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
  name: msg-gateway-ingress
spec:
  rules:
    - host: k8s.open-im-test.rentsoft.cn
      http:
        paths:
          - backend:
              service:
                serviceName: msg-gateway
                servicePort: 10001
            path: /msg-gateway/(.*)
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
     # 使用重写后的路径进行路由
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
  name: api-ingress
spec:
  rules:
    - host: k8s.open-im-test.rentsoft.cn
      http:
        paths:
          - backend:
              service:
                name: api
                port:
                  number: 10002
            path: /api/(.*)
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
     # 使用重写后的路径进行路由
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
  name: demo-ingress
spec:
  rules:
    - host: k8s.open-im-test.rentsoft.cn
      http:
        paths:
          - backend:
              service:
                name: demo
                port:
                  number: 10004
            path: /demo/(.*)
            pathType: Prefix
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
     # 使用重写后的路径进行路由
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: "/$1"
  name: cms-api-ingress
spec:
  rules:
    - host: k8s.open-im-test.rentsoft.cn
      http:
        paths:
          - backend:
              service:
                name: cms-api
                port:
                  number: 10006
            path: /cms-api/(.*)
            pathType: Prefix
