definitions:
  base_info.UpdateSelfUserInfoReq:
    properties:
      birth:
        type: integer
      email:
        maxLength: 64
        type: string
      ex:
        maxLength: 1024
        type: string
      faceURL:
        maxLength: 1024
        type: string
      gender:
        enum:
        - 0
        - 1
        - 2
        type: integer
      nickname:
        maxLength: 64
        minLength: 1
        type: string
      operationID:
        type: string
      phoneNumber:
        maxLength: 32
        type: string
      userID:
        maxLength: 64
        minLength: 1
        type: string
    required:
    - operationID
    - userID
    type: object
  base_info.UpdateUserInfoResp:
    properties:
      errCode:
        type: integer
      errMsg:
        type: string
    type: object
info:
  contact: {}
paths:
  /user/update_user_info:
    post:
      consumes:
      - application/json
      description: 修改用户信息 userID faceURL等
      operationId: UpdateUserInfo
      parameters:
      - description: im token
        in: header
        name: token
        required: true
        type: string
      - description: 请求
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/base_info.UpdateSelfUserInfoReq'
      produces:
      - application/json
      responses:
        "0":
          description: ""
          schema:
            $ref: '#/definitions/base_info.UpdateUserInfoResp'
        "400":
          description: errCode为400 一般为参数输入错误, token未带上等
          schema:
            $ref: '#/definitions/base_info.UpdateUserInfoResp'
        "500":
          description: errCode为500 一般为服务器内部错误
          schema:
            $ref: '#/definitions/base_info.UpdateUserInfoResp'
      summary: 修改用户信息
      tags:
      - 用户信息
swagger: "2.0"
