etcd:
  userName:
  password:

mysql:
  dbMysqlUserName: root #mysql用户名，建议修改
  dbMysqlPassword: openIM123 # mysql密码，建议修改

mongo:
  dbUserName: root #mongo用户名，建议先不设置
  dbPassword: openIM123  #mongo密码，建议先不设置

redis:
  dbUserName:
  dbPassWord: openIM123 #redis密码 建议修改

kafka:
  SASLUserName:
  SASLPassword:

credential:
  minio:
    endpoint: http://127.0.0.1:10005 #发图片视频文件需要填写
    accessKeyID: root
    secretAccessKey: openIM123

secret: tuoyun

tokenpolicy:
  accessSecret: "open_im_server" #token生成相关，默认即可
  accessExpire: 90 #token过期时间（天） 默认即可

messageverify:
  friendVerify: false

push:
  getui:  #个推推送
    pushUrl: "https://restapi.getui.com/v2/$appId"
    masterSecret: ""
    appKey: ""
    enable: false

