#more prometheus-compose.yml 
global:
  scrape_interval:     15s 
  evaluation_interval: 15s 

scrape_configs:
    - job_name: 'prometheus'
      static_configs:
      - targets: ['localhost:10007']
    - job_name: 'openIM-server'
      metrics_path: /cms/prometheus/metrics
      static_configs:
      - targets: ['localhost:10006']  
     