---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: transfer-deployment
spec:
  selector:
    matchLabels:
      app: transfer # 选择这个指定标签执行
  replicas: 2 # 运行pod数量
  template:
    metadata:
      labels:
        app: transfer # 标签
    spec:
      containers:
      - name: transfer
        image: openim/transfer:v2.0.10
        volumeMounts:
          - name: config
            mountPath: /Open-IM-Server/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: config
  strategy: #更新策略
    type: RollingUpdate # 滚动更新
